[application]

[web.app]

# HTML title tag content
title = "bearcove"

# include `assets` in web platform
[web.resource]

# Assets directory
dir = "assets"

# Additional CSS style files
style = []

# Additional JavaScript files
script = []

[web.resource.dev]

# Javascript code file
# serve: [dev-server] only
script = []
